#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="aprajitaretails")]
public partial class Aprajitaretails : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBank(Bank instance);
  partial void UpdateBank(Bank instance);
  partial void DeleteBank(Bank instance);
  partial void InsertBankDetail(BankDetail instance);
  partial void UpdateBankDetail(BankDetail instance);
  partial void DeleteBankDetail(BankDetail instance);
  partial void InsertCustomer(Customer instance);
  partial void UpdateCustomer(Customer instance);
  partial void DeleteCustomer(Customer instance);
  partial void InsertDailySale(DailySale instance);
  partial void UpdateDailySale(DailySale instance);
  partial void DeleteDailySale(DailySale instance);
  partial void InsertEmployee(Employee instance);
  partial void UpdateEmployee(Employee instance);
  partial void DeleteEmployee(Employee instance);
  partial void InsertExpense(Expense instance);
  partial void UpdateExpense(Expense instance);
  partial void DeleteExpense(Expense instance);
  partial void InsertExpensesCategory(ExpensesCategory instance);
  partial void UpdateExpensesCategory(ExpensesCategory instance);
  partial void DeleteExpensesCategory(ExpensesCategory instance);
  partial void InsertPaymentMode(PaymentMode instance);
  partial void UpdatePaymentMode(PaymentMode instance);
  partial void DeletePaymentMode(PaymentMode instance);
  partial void InsertProductItem(ProductItem instance);
  partial void UpdateProductItem(ProductItem instance);
  partial void DeleteProductItem(ProductItem instance);
  partial void InsertPurchase(Purchase instance);
  partial void UpdatePurchase(Purchase instance);
  partial void DeletePurchase(Purchase instance);
  partial void InsertPurchaseRegister(PurchaseRegister instance);
  partial void UpdatePurchaseRegister(PurchaseRegister instance);
  partial void DeletePurchaseRegister(PurchaseRegister instance);
  partial void InsertSale(Sale instance);
  partial void UpdateSale(Sale instance);
  partial void DeleteSale(Sale instance);
  partial void InsertSalesRegister(SalesRegister instance);
  partial void UpdateSalesRegister(SalesRegister instance);
  partial void DeleteSalesRegister(SalesRegister instance);
  #endregion
	
	public Aprajitaretails(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Aprajitaretails(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Aprajitaretails(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public Aprajitaretails(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Bank> Banks
	{
		get
		{
			return this.GetTable<Bank>();
		}
	}
	
	public System.Data.Linq.Table<BankDetail> BankDetails
	{
		get
		{
			return this.GetTable<BankDetail>();
		}
	}
	
	public System.Data.Linq.Table<Customer> Customers
	{
		get
		{
			return this.GetTable<Customer>();
		}
	}
	
	public System.Data.Linq.Table<DailySale> DailySales
	{
		get
		{
			return this.GetTable<DailySale>();
		}
	}
	
	public System.Data.Linq.Table<Employee> Employees
	{
		get
		{
			return this.GetTable<Employee>();
		}
	}
	
	public System.Data.Linq.Table<Expense> Expenses
	{
		get
		{
			return this.GetTable<Expense>();
		}
	}
	
	public System.Data.Linq.Table<ExpensesCategory> ExpensesCategories
	{
		get
		{
			return this.GetTable<ExpensesCategory>();
		}
	}
	
	public System.Data.Linq.Table<PaymentMode> PaymentModes
	{
		get
		{
			return this.GetTable<PaymentMode>();
		}
	}
	
	public System.Data.Linq.Table<ProductItem> ProductItems
	{
		get
		{
			return this.GetTable<ProductItem>();
		}
	}
	
	public System.Data.Linq.Table<Purchase> Purchases
	{
		get
		{
			return this.GetTable<Purchase>();
		}
	}
	
	public System.Data.Linq.Table<PurchaseRegister> PurchaseRegisters
	{
		get
		{
			return this.GetTable<PurchaseRegister>();
		}
	}
	
	public System.Data.Linq.Table<Sale> Sales
	{
		get
		{
			return this.GetTable<Sale>();
		}
	}
	
	public System.Data.Linq.Table<SalesRegister> SalesRegisters
	{
		get
		{
			return this.GetTable<SalesRegister>();
		}
	}
	
	public System.Data.Linq.Table<User> Users
	{
		get
		{
			return this.GetTable<User>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bank")]
public partial class Bank : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _BankName;
	
	private string _AccountNo;
	
	private System.Nullable<int> _AccountType;
	
	private string _IFSCCode;
	
	private string _Branch;
	
	private string _BranchCity;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnBankNameChanging(string value);
    partial void OnBankNameChanged();
    partial void OnAccountNoChanging(string value);
    partial void OnAccountNoChanged();
    partial void OnAccountTypeChanging(System.Nullable<int> value);
    partial void OnAccountTypeChanged();
    partial void OnIFSCCodeChanging(string value);
    partial void OnIFSCCodeChanged();
    partial void OnBranchChanging(string value);
    partial void OnBranchChanged();
    partial void OnBranchCityChanging(string value);
    partial void OnBranchCityChanged();
    #endregion
	
	public Bank()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankName", DbType="VarChar(100)")]
	public string BankName
	{
		get
		{
			return this._BankName;
		}
		set
		{
			if ((this._BankName != value))
			{
				this.OnBankNameChanging(value);
				this.SendPropertyChanging();
				this._BankName = value;
				this.SendPropertyChanged("BankName");
				this.OnBankNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountNo", DbType="VarChar(100)")]
	public string AccountNo
	{
		get
		{
			return this._AccountNo;
		}
		set
		{
			if ((this._AccountNo != value))
			{
				this.OnAccountNoChanging(value);
				this.SendPropertyChanging();
				this._AccountNo = value;
				this.SendPropertyChanged("AccountNo");
				this.OnAccountNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AccountType", DbType="Int")]
	public System.Nullable<int> AccountType
	{
		get
		{
			return this._AccountType;
		}
		set
		{
			if ((this._AccountType != value))
			{
				this.OnAccountTypeChanging(value);
				this.SendPropertyChanging();
				this._AccountType = value;
				this.SendPropertyChanged("AccountType");
				this.OnAccountTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IFSCCode", DbType="VarChar(100)")]
	public string IFSCCode
	{
		get
		{
			return this._IFSCCode;
		}
		set
		{
			if ((this._IFSCCode != value))
			{
				this.OnIFSCCodeChanging(value);
				this.SendPropertyChanging();
				this._IFSCCode = value;
				this.SendPropertyChanged("IFSCCode");
				this.OnIFSCCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Branch", DbType="VarChar(100)")]
	public string Branch
	{
		get
		{
			return this._Branch;
		}
		set
		{
			if ((this._Branch != value))
			{
				this.OnBranchChanging(value);
				this.SendPropertyChanging();
				this._Branch = value;
				this.SendPropertyChanged("Branch");
				this.OnBranchChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BranchCity", DbType="VarChar(100)")]
	public string BranchCity
	{
		get
		{
			return this._BranchCity;
		}
		set
		{
			if ((this._BranchCity != value))
			{
				this.OnBranchCityChanging(value);
				this.SendPropertyChanging();
				this._BranchCity = value;
				this.SendPropertyChanged("BranchCity");
				this.OnBranchCityChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BankDetails")]
public partial class BankDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _RefID;
	
	private System.Nullable<int> _BankID;
	
	private System.Nullable<int> _TranscationType;
	
	private string _BankRef;
	
	private string _TranscationRef;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnRefIDChanging(string value);
    partial void OnRefIDChanged();
    partial void OnBankIDChanging(System.Nullable<int> value);
    partial void OnBankIDChanged();
    partial void OnTranscationTypeChanging(System.Nullable<int> value);
    partial void OnTranscationTypeChanged();
    partial void OnBankRefChanging(string value);
    partial void OnBankRefChanged();
    partial void OnTranscationRefChanging(string value);
    partial void OnTranscationRefChanged();
    #endregion
	
	public BankDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RefID", DbType="VarChar(100)")]
	public string RefID
	{
		get
		{
			return this._RefID;
		}
		set
		{
			if ((this._RefID != value))
			{
				this.OnRefIDChanging(value);
				this.SendPropertyChanging();
				this._RefID = value;
				this.SendPropertyChanged("RefID");
				this.OnRefIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankID", DbType="Int")]
	public System.Nullable<int> BankID
	{
		get
		{
			return this._BankID;
		}
		set
		{
			if ((this._BankID != value))
			{
				this.OnBankIDChanging(value);
				this.SendPropertyChanging();
				this._BankID = value;
				this.SendPropertyChanged("BankID");
				this.OnBankIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranscationType", DbType="Int")]
	public System.Nullable<int> TranscationType
	{
		get
		{
			return this._TranscationType;
		}
		set
		{
			if ((this._TranscationType != value))
			{
				this.OnTranscationTypeChanging(value);
				this.SendPropertyChanging();
				this._TranscationType = value;
				this.SendPropertyChanged("TranscationType");
				this.OnTranscationTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankRef", DbType="VarChar(100)")]
	public string BankRef
	{
		get
		{
			return this._BankRef;
		}
		set
		{
			if ((this._BankRef != value))
			{
				this.OnBankRefChanging(value);
				this.SendPropertyChanging();
				this._BankRef = value;
				this.SendPropertyChanged("BankRef");
				this.OnBankRefChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TranscationRef", DbType="VarChar(100)")]
	public string TranscationRef
	{
		get
		{
			return this._TranscationRef;
		}
		set
		{
			if ((this._TranscationRef != value))
			{
				this.OnTranscationRefChanging(value);
				this.SendPropertyChanging();
				this._TranscationRef = value;
				this.SendPropertyChanged("TranscationRef");
				this.OnTranscationRefChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Customer")]
public partial class Customer : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _Age;
	
	private string _FirstName;
	
	private string _LastName;
	
	private string _City;
	
	private string _MobileNo;
	
	private System.Nullable<int> _Gender;
	
	private System.Nullable<int> _NoOfBills;
	
	private System.Nullable<decimal> _TotalAmount;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnNoOfBillsChanging(System.Nullable<int> value);
    partial void OnNoOfBillsChanged();
    partial void OnTotalAmountChanging(System.Nullable<decimal> value);
    partial void OnTotalAmountChanged();
    #endregion
	
	public Customer()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
	public System.Nullable<int> Age
	{
		get
		{
			return this._Age;
		}
		set
		{
			if ((this._Age != value))
			{
				this.OnAgeChanging(value);
				this.SendPropertyChanging();
				this._Age = value;
				this.SendPropertyChanged("Age");
				this.OnAgeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(100)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this.OnMobileNoChanging(value);
				this.SendPropertyChanging();
				this._MobileNo = value;
				this.SendPropertyChanged("MobileNo");
				this.OnMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoOfBills", DbType="Int")]
	public System.Nullable<int> NoOfBills
	{
		get
		{
			return this._NoOfBills;
		}
		set
		{
			if ((this._NoOfBills != value))
			{
				this.OnNoOfBillsChanging(value);
				this.SendPropertyChanging();
				this._NoOfBills = value;
				this.SendPropertyChanged("NoOfBills");
				this.OnNoOfBillsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TotalAmount", DbType="Money")]
	public System.Nullable<decimal> TotalAmount
	{
		get
		{
			return this._TotalAmount;
		}
		set
		{
			if ((this._TotalAmount != value))
			{
				this.OnTotalAmountChanging(value);
				this.SendPropertyChanging();
				this._TotalAmount = value;
				this.SendPropertyChanged("TotalAmount");
				this.OnTotalAmountChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DailySale")]
public partial class DailySale : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<System.DateTime> _SaleDate;
	
	private System.Nullable<int> _CustomerID;
	
	private string _InvoiceNo;
	
	private System.Nullable<decimal> _Amount;
	
	private System.Nullable<decimal> _Discount;
	
	private System.Nullable<int> _RMZ;
	
	private System.Nullable<int> _Fabric;
	
	private System.Nullable<int> _Tailoring;
	
	private System.Nullable<int> _PaymentMode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSaleDateChanging(System.Nullable<System.DateTime> value);
    partial void OnSaleDateChanged();
    partial void OnCustomerIDChanging(System.Nullable<int> value);
    partial void OnCustomerIDChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnDiscountChanging(System.Nullable<decimal> value);
    partial void OnDiscountChanged();
    partial void OnRMZChanging(System.Nullable<int> value);
    partial void OnRMZChanged();
    partial void OnFabricChanging(System.Nullable<int> value);
    partial void OnFabricChanged();
    partial void OnTailoringChanging(System.Nullable<int> value);
    partial void OnTailoringChanged();
    partial void OnPaymentModeChanging(System.Nullable<int> value);
    partial void OnPaymentModeChanged();
    #endregion
	
	public DailySale()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> SaleDate
	{
		get
		{
			return this._SaleDate;
		}
		set
		{
			if ((this._SaleDate != value))
			{
				this.OnSaleDateChanging(value);
				this.SendPropertyChanging();
				this._SaleDate = value;
				this.SendPropertyChanged("SaleDate");
				this.OnSaleDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomerID", DbType="Int")]
	public System.Nullable<int> CustomerID
	{
		get
		{
			return this._CustomerID;
		}
		set
		{
			if ((this._CustomerID != value))
			{
				this.OnCustomerIDChanging(value);
				this.SendPropertyChanging();
				this._CustomerID = value;
				this.SendPropertyChanged("CustomerID");
				this.OnCustomerIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="VarChar(100)")]
	public string InvoiceNo
	{
		get
		{
			return this._InvoiceNo;
		}
		set
		{
			if ((this._InvoiceNo != value))
			{
				this.OnInvoiceNoChanging(value);
				this.SendPropertyChanging();
				this._InvoiceNo = value;
				this.SendPropertyChanged("InvoiceNo");
				this.OnInvoiceNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
	public System.Nullable<decimal> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Money")]
	public System.Nullable<decimal> Discount
	{
		get
		{
			return this._Discount;
		}
		set
		{
			if ((this._Discount != value))
			{
				this.OnDiscountChanging(value);
				this.SendPropertyChanging();
				this._Discount = value;
				this.SendPropertyChanged("Discount");
				this.OnDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RMZ", DbType="Int")]
	public System.Nullable<int> RMZ
	{
		get
		{
			return this._RMZ;
		}
		set
		{
			if ((this._RMZ != value))
			{
				this.OnRMZChanging(value);
				this.SendPropertyChanging();
				this._RMZ = value;
				this.SendPropertyChanged("RMZ");
				this.OnRMZChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fabric", DbType="Int")]
	public System.Nullable<int> Fabric
	{
		get
		{
			return this._Fabric;
		}
		set
		{
			if ((this._Fabric != value))
			{
				this.OnFabricChanging(value);
				this.SendPropertyChanging();
				this._Fabric = value;
				this.SendPropertyChanged("Fabric");
				this.OnFabricChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tailoring", DbType="Int")]
	public System.Nullable<int> Tailoring
	{
		get
		{
			return this._Tailoring;
		}
		set
		{
			if ((this._Tailoring != value))
			{
				this.OnTailoringChanging(value);
				this.SendPropertyChanging();
				this._Tailoring = value;
				this.SendPropertyChanged("Tailoring");
				this.OnTailoringChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMode", DbType="Int")]
	public System.Nullable<int> PaymentMode
	{
		get
		{
			return this._PaymentMode;
		}
		set
		{
			if ((this._PaymentMode != value))
			{
				this.OnPaymentModeChanging(value);
				this.SendPropertyChanging();
				this._PaymentMode = value;
				this.SendPropertyChanged("PaymentMode");
				this.OnPaymentModeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _EMPCode;
	
	private string _FirstName;
	
	private string _LastName;
	
	private System.Nullable<int> _Age;
	
	private System.Nullable<int> _Gender;
	
	private string _AddressLine1;
	
	private string _City;
	
	private string _Country;
	
	private string _State;
	
	private System.Nullable<int> _EmpType;
	
	private System.Nullable<int> _AttendenceId;
	
	private System.Nullable<System.DateTime> _DateOfBirth;
	
	private System.Nullable<System.DateTime> _DateOfJoining;
	
	private System.Nullable<System.DateTime> _DateOfLeaving;
	
	private string _MobileNo;
	
	private string _Status;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnEMPCodeChanging(string value);
    partial void OnEMPCodeChanged();
    partial void OnFirstNameChanging(string value);
    partial void OnFirstNameChanged();
    partial void OnLastNameChanging(string value);
    partial void OnLastNameChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnGenderChanging(System.Nullable<int> value);
    partial void OnGenderChanged();
    partial void OnAddressLine1Changing(string value);
    partial void OnAddressLine1Changed();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnCountryChanging(string value);
    partial void OnCountryChanged();
    partial void OnStateChanging(string value);
    partial void OnStateChanged();
    partial void OnEmpTypeChanging(System.Nullable<int> value);
    partial void OnEmpTypeChanged();
    partial void OnAttendenceIdChanging(System.Nullable<int> value);
    partial void OnAttendenceIdChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnDateOfJoiningChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfJoiningChanged();
    partial void OnDateOfLeavingChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfLeavingChanged();
    partial void OnMobileNoChanging(string value);
    partial void OnMobileNoChanged();
    partial void OnStatusChanging(string value);
    partial void OnStatusChanged();
    #endregion
	
	public Employee()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMPCode", DbType="VarChar(100)")]
	public string EMPCode
	{
		get
		{
			return this._EMPCode;
		}
		set
		{
			if ((this._EMPCode != value))
			{
				this.OnEMPCodeChanging(value);
				this.SendPropertyChanging();
				this._EMPCode = value;
				this.SendPropertyChanged("EMPCode");
				this.OnEMPCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FirstName", DbType="VarChar(100)")]
	public string FirstName
	{
		get
		{
			return this._FirstName;
		}
		set
		{
			if ((this._FirstName != value))
			{
				this.OnFirstNameChanging(value);
				this.SendPropertyChanging();
				this._FirstName = value;
				this.SendPropertyChanged("FirstName");
				this.OnFirstNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastName", DbType="VarChar(100)")]
	public string LastName
	{
		get
		{
			return this._LastName;
		}
		set
		{
			if ((this._LastName != value))
			{
				this.OnLastNameChanging(value);
				this.SendPropertyChanging();
				this._LastName = value;
				this.SendPropertyChanged("LastName");
				this.OnLastNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
	public System.Nullable<int> Age
	{
		get
		{
			return this._Age;
		}
		set
		{
			if ((this._Age != value))
			{
				this.OnAgeChanging(value);
				this.SendPropertyChanging();
				this._Age = value;
				this.SendPropertyChanged("Age");
				this.OnAgeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gender", DbType="Int")]
	public System.Nullable<int> Gender
	{
		get
		{
			return this._Gender;
		}
		set
		{
			if ((this._Gender != value))
			{
				this.OnGenderChanging(value);
				this.SendPropertyChanging();
				this._Gender = value;
				this.SendPropertyChanged("Gender");
				this.OnGenderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AddressLine1", DbType="VarChar(100)")]
	public string AddressLine1
	{
		get
		{
			return this._AddressLine1;
		}
		set
		{
			if ((this._AddressLine1 != value))
			{
				this.OnAddressLine1Changing(value);
				this.SendPropertyChanging();
				this._AddressLine1 = value;
				this.SendPropertyChanged("AddressLine1");
				this.OnAddressLine1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_City", DbType="VarChar(100)")]
	public string City
	{
		get
		{
			return this._City;
		}
		set
		{
			if ((this._City != value))
			{
				this.OnCityChanging(value);
				this.SendPropertyChanging();
				this._City = value;
				this.SendPropertyChanged("City");
				this.OnCityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Country", DbType="VarChar(100)")]
	public string Country
	{
		get
		{
			return this._Country;
		}
		set
		{
			if ((this._Country != value))
			{
				this.OnCountryChanging(value);
				this.SendPropertyChanging();
				this._Country = value;
				this.SendPropertyChanged("Country");
				this.OnCountryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="VarChar(100)")]
	public string State
	{
		get
		{
			return this._State;
		}
		set
		{
			if ((this._State != value))
			{
				this.OnStateChanging(value);
				this.SendPropertyChanging();
				this._State = value;
				this.SendPropertyChanged("State");
				this.OnStateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmpType", DbType="Int")]
	public System.Nullable<int> EmpType
	{
		get
		{
			return this._EmpType;
		}
		set
		{
			if ((this._EmpType != value))
			{
				this.OnEmpTypeChanging(value);
				this.SendPropertyChanging();
				this._EmpType = value;
				this.SendPropertyChanged("EmpType");
				this.OnEmpTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttendenceId", DbType="Int")]
	public System.Nullable<int> AttendenceId
	{
		get
		{
			return this._AttendenceId;
		}
		set
		{
			if ((this._AttendenceId != value))
			{
				this.OnAttendenceIdChanging(value);
				this.SendPropertyChanging();
				this._AttendenceId = value;
				this.SendPropertyChanged("AttendenceId");
				this.OnAttendenceIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfBirth", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateOfBirth
	{
		get
		{
			return this._DateOfBirth;
		}
		set
		{
			if ((this._DateOfBirth != value))
			{
				this.OnDateOfBirthChanging(value);
				this.SendPropertyChanging();
				this._DateOfBirth = value;
				this.SendPropertyChanged("DateOfBirth");
				this.OnDateOfBirthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfJoining", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateOfJoining
	{
		get
		{
			return this._DateOfJoining;
		}
		set
		{
			if ((this._DateOfJoining != value))
			{
				this.OnDateOfJoiningChanging(value);
				this.SendPropertyChanging();
				this._DateOfJoining = value;
				this.SendPropertyChanged("DateOfJoining");
				this.OnDateOfJoiningChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateOfLeaving", DbType="DateTime")]
	public System.Nullable<System.DateTime> DateOfLeaving
	{
		get
		{
			return this._DateOfLeaving;
		}
		set
		{
			if ((this._DateOfLeaving != value))
			{
				this.OnDateOfLeavingChanging(value);
				this.SendPropertyChanging();
				this._DateOfLeaving = value;
				this.SendPropertyChanged("DateOfLeaving");
				this.OnDateOfLeavingChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MobileNo", DbType="VarChar(100)")]
	public string MobileNo
	{
		get
		{
			return this._MobileNo;
		}
		set
		{
			if ((this._MobileNo != value))
			{
				this.OnMobileNoChanging(value);
				this.SendPropertyChanging();
				this._MobileNo = value;
				this.SendPropertyChanged("MobileNo");
				this.OnMobileNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="VarChar(100)")]
	public string Status
	{
		get
		{
			return this._Status;
		}
		set
		{
			if ((this._Status != value))
			{
				this.OnStatusChanging(value);
				this.SendPropertyChanging();
				this._Status = value;
				this.SendPropertyChanged("Status");
				this.OnStatusChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Expenses")]
public partial class Expense : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private System.Nullable<int> _ExpensesCategoryID;
	
	private string _ExpensesReason;
	
	private string _ApprovedBy;
	
	private System.Nullable<int> _PaymentModeID;
	
	private System.Nullable<decimal> _Amount;
	
	private System.Nullable<int> _BankDetailsID;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnExpensesCategoryIDChanging(System.Nullable<int> value);
    partial void OnExpensesCategoryIDChanged();
    partial void OnExpensesReasonChanging(string value);
    partial void OnExpensesReasonChanged();
    partial void OnApprovedByChanging(string value);
    partial void OnApprovedByChanged();
    partial void OnPaymentModeIDChanging(System.Nullable<int> value);
    partial void OnPaymentModeIDChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnBankDetailsIDChanging(System.Nullable<int> value);
    partial void OnBankDetailsIDChanged();
    #endregion
	
	public Expense()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpensesCategoryID", DbType="Int")]
	public System.Nullable<int> ExpensesCategoryID
	{
		get
		{
			return this._ExpensesCategoryID;
		}
		set
		{
			if ((this._ExpensesCategoryID != value))
			{
				this.OnExpensesCategoryIDChanging(value);
				this.SendPropertyChanging();
				this._ExpensesCategoryID = value;
				this.SendPropertyChanged("ExpensesCategoryID");
				this.OnExpensesCategoryIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExpensesReason", DbType="VarChar(100)")]
	public string ExpensesReason
	{
		get
		{
			return this._ExpensesReason;
		}
		set
		{
			if ((this._ExpensesReason != value))
			{
				this.OnExpensesReasonChanging(value);
				this.SendPropertyChanging();
				this._ExpensesReason = value;
				this.SendPropertyChanged("ExpensesReason");
				this.OnExpensesReasonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ApprovedBy", DbType="VarChar(100)")]
	public string ApprovedBy
	{
		get
		{
			return this._ApprovedBy;
		}
		set
		{
			if ((this._ApprovedBy != value))
			{
				this.OnApprovedByChanging(value);
				this.SendPropertyChanging();
				this._ApprovedBy = value;
				this.SendPropertyChanged("ApprovedBy");
				this.OnApprovedByChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentModeID", DbType="Int")]
	public System.Nullable<int> PaymentModeID
	{
		get
		{
			return this._PaymentModeID;
		}
		set
		{
			if ((this._PaymentModeID != value))
			{
				this.OnPaymentModeIDChanging(value);
				this.SendPropertyChanging();
				this._PaymentModeID = value;
				this.SendPropertyChanged("PaymentModeID");
				this.OnPaymentModeIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Amount", DbType="Money")]
	public System.Nullable<decimal> Amount
	{
		get
		{
			return this._Amount;
		}
		set
		{
			if ((this._Amount != value))
			{
				this.OnAmountChanging(value);
				this.SendPropertyChanging();
				this._Amount = value;
				this.SendPropertyChanged("Amount");
				this.OnAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BankDetailsID", DbType="Int")]
	public System.Nullable<int> BankDetailsID
	{
		get
		{
			return this._BankDetailsID;
		}
		set
		{
			if ((this._BankDetailsID != value))
			{
				this.OnBankDetailsIDChanging(value);
				this.SendPropertyChanging();
				this._BankDetailsID = value;
				this.SendPropertyChanged("BankDetailsID");
				this.OnBankDetailsIDChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ExpensesCategory")]
public partial class ExpensesCategory : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Category;
	
	private System.Nullable<int> _Level;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnLevelChanging(System.Nullable<int> value);
    partial void OnLevelChanged();
    #endregion
	
	public ExpensesCategory()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="VarChar(100)")]
	public string Category
	{
		get
		{
			return this._Category;
		}
		set
		{
			if ((this._Category != value))
			{
				this.OnCategoryChanging(value);
				this.SendPropertyChanging();
				this._Category = value;
				this.SendPropertyChanged("Category");
				this.OnCategoryChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Level", DbType="Int")]
	public System.Nullable<int> Level
	{
		get
		{
			return this._Level;
		}
		set
		{
			if ((this._Level != value))
			{
				this.OnLevelChanging(value);
				this.SendPropertyChanging();
				this._Level = value;
				this.SendPropertyChanged("Level");
				this.OnLevelChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PaymentMode")]
public partial class PaymentMode : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _PayMode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnPayModeChanging(string value);
    partial void OnPayModeChanged();
    #endregion
	
	public PaymentMode()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PayMode", DbType="VarChar(50)")]
	public string PayMode
	{
		get
		{
			return this._PayMode;
		}
		set
		{
			if ((this._PayMode != value))
			{
				this.OnPayModeChanging(value);
				this.SendPropertyChanging();
				this._PayMode = value;
				this.SendPropertyChanged("PayMode");
				this.OnPayModeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ProductItems")]
public partial class ProductItem : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _StyleCode;
	
	private string _Barcode;
	
	private string _SupplierId;
	
	private string _BrandName;
	
	private string _ProductName;
	
	private string _ItemDesc;
	
	private System.Nullable<decimal> _MRP;
	
	private System.Nullable<decimal> _Tax;
	
	private System.Nullable<decimal> _Cost;
	
	private string _Size;
	
	private System.Nullable<decimal> _Qty;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnStyleCodeChanging(string value);
    partial void OnStyleCodeChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnSupplierIdChanging(string value);
    partial void OnSupplierIdChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnItemDescChanging(string value);
    partial void OnItemDescChanged();
    partial void OnMRPChanging(System.Nullable<decimal> value);
    partial void OnMRPChanged();
    partial void OnTaxChanging(System.Nullable<decimal> value);
    partial void OnTaxChanged();
    partial void OnCostChanging(System.Nullable<decimal> value);
    partial void OnCostChanged();
    partial void OnSizeChanging(string value);
    partial void OnSizeChanged();
    partial void OnQtyChanging(System.Nullable<decimal> value);
    partial void OnQtyChanged();
    #endregion
	
	public ProductItem()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleCode", DbType="VarChar(100)")]
	public string StyleCode
	{
		get
		{
			return this._StyleCode;
		}
		set
		{
			if ((this._StyleCode != value))
			{
				this.OnStyleCodeChanging(value);
				this.SendPropertyChanging();
				this._StyleCode = value;
				this.SendPropertyChanged("StyleCode");
				this.OnStyleCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="VarChar(100)")]
	public string Barcode
	{
		get
		{
			return this._Barcode;
		}
		set
		{
			if ((this._Barcode != value))
			{
				this.OnBarcodeChanging(value);
				this.SendPropertyChanging();
				this._Barcode = value;
				this.SendPropertyChanged("Barcode");
				this.OnBarcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierId", DbType="VarChar(100)")]
	public string SupplierId
	{
		get
		{
			return this._SupplierId;
		}
		set
		{
			if ((this._SupplierId != value))
			{
				this.OnSupplierIdChanging(value);
				this.SendPropertyChanging();
				this._SupplierId = value;
				this.SendPropertyChanged("SupplierId");
				this.OnSupplierIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="VarChar(100)")]
	public string BrandName
	{
		get
		{
			return this._BrandName;
		}
		set
		{
			if ((this._BrandName != value))
			{
				this.OnBrandNameChanging(value);
				this.SendPropertyChanging();
				this._BrandName = value;
				this.SendPropertyChanged("BrandName");
				this.OnBrandNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(100)")]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDesc", DbType="VarChar(100)")]
	public string ItemDesc
	{
		get
		{
			return this._ItemDesc;
		}
		set
		{
			if ((this._ItemDesc != value))
			{
				this.OnItemDescChanging(value);
				this.SendPropertyChanging();
				this._ItemDesc = value;
				this.SendPropertyChanged("ItemDesc");
				this.OnItemDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Money")]
	public System.Nullable<decimal> MRP
	{
		get
		{
			return this._MRP;
		}
		set
		{
			if ((this._MRP != value))
			{
				this.OnMRPChanging(value);
				this.SendPropertyChanging();
				this._MRP = value;
				this.SendPropertyChanged("MRP");
				this.OnMRPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tax", DbType="Money")]
	public System.Nullable<decimal> Tax
	{
		get
		{
			return this._Tax;
		}
		set
		{
			if ((this._Tax != value))
			{
				this.OnTaxChanging(value);
				this.SendPropertyChanging();
				this._Tax = value;
				this.SendPropertyChanged("Tax");
				this.OnTaxChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money")]
	public System.Nullable<decimal> Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Size", DbType="VarChar(100)")]
	public string Size
	{
		get
		{
			return this._Size;
		}
		set
		{
			if ((this._Size != value))
			{
				this.OnSizeChanging(value);
				this.SendPropertyChanging();
				this._Size = value;
				this.SendPropertyChanged("Size");
				this.OnSizeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Money")]
	public System.Nullable<decimal> Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this.OnQtyChanging(value);
				this.SendPropertyChanging();
				this._Qty = value;
				this.SendPropertyChanged("Qty");
				this.OnQtyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.purchase")]
public partial class Purchase : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _GRNNo;
	
	private System.Nullable<System.DateTime> _GRNDate;
	
	private string _InvoiceNo;
	
	private System.Nullable<System.DateTime> _InvoiceDate;
	
	private string _SupplierName;
	
	private string _Barcode;
	
	private string _ProductName;
	
	private string _StyleCode;
	
	private string _ItemDesc;
	
	private System.Nullable<double> _Quantity;
	
	private System.Nullable<decimal> _MRP;
	
	private System.Nullable<decimal> _MRPValue;
	
	private System.Nullable<decimal> _Cost;
	
	private System.Nullable<decimal> _CostValue;
	
	private System.Nullable<decimal> _TaxAmt;
	
	private System.DateTime _ImportDate;
	
	private string _IsDataConsumed;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGRNNoChanging(string value);
    partial void OnGRNNoChanged();
    partial void OnGRNDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGRNDateChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnInvoiceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceDateChanged();
    partial void OnSupplierNameChanging(string value);
    partial void OnSupplierNameChanged();
    partial void OnBarcodeChanging(string value);
    partial void OnBarcodeChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnStyleCodeChanging(string value);
    partial void OnStyleCodeChanged();
    partial void OnItemDescChanging(string value);
    partial void OnItemDescChanged();
    partial void OnQuantityChanging(System.Nullable<double> value);
    partial void OnQuantityChanged();
    partial void OnMRPChanging(System.Nullable<decimal> value);
    partial void OnMRPChanged();
    partial void OnMRPValueChanging(System.Nullable<decimal> value);
    partial void OnMRPValueChanged();
    partial void OnCostChanging(System.Nullable<decimal> value);
    partial void OnCostChanged();
    partial void OnCostValueChanging(System.Nullable<decimal> value);
    partial void OnCostValueChanged();
    partial void OnTaxAmtChanging(System.Nullable<decimal> value);
    partial void OnTaxAmtChanged();
    partial void OnImportDateChanging(System.DateTime value);
    partial void OnImportDateChanged();
    partial void OnIsDataConsumedChanging(string value);
    partial void OnIsDataConsumedChanged();
    #endregion
	
	public Purchase()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNNo", DbType="VarChar(50)")]
	public string GRNNo
	{
		get
		{
			return this._GRNNo;
		}
		set
		{
			if ((this._GRNNo != value))
			{
				this.OnGRNNoChanging(value);
				this.SendPropertyChanging();
				this._GRNNo = value;
				this.SendPropertyChanged("GRNNo");
				this.OnGRNNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNDate", DbType="Date")]
	public System.Nullable<System.DateTime> GRNDate
	{
		get
		{
			return this._GRNDate;
		}
		set
		{
			if ((this._GRNDate != value))
			{
				this.OnGRNDateChanging(value);
				this.SendPropertyChanging();
				this._GRNDate = value;
				this.SendPropertyChanged("GRNDate");
				this.OnGRNDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="VarChar(50)")]
	public string InvoiceNo
	{
		get
		{
			return this._InvoiceNo;
		}
		set
		{
			if ((this._InvoiceNo != value))
			{
				this.OnInvoiceNoChanging(value);
				this.SendPropertyChanging();
				this._InvoiceNo = value;
				this.SendPropertyChanged("InvoiceNo");
				this.OnInvoiceNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="Date")]
	public System.Nullable<System.DateTime> InvoiceDate
	{
		get
		{
			return this._InvoiceDate;
		}
		set
		{
			if ((this._InvoiceDate != value))
			{
				this.OnInvoiceDateChanging(value);
				this.SendPropertyChanging();
				this._InvoiceDate = value;
				this.SendPropertyChanged("InvoiceDate");
				this.OnInvoiceDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="VarChar(50)")]
	public string SupplierName
	{
		get
		{
			return this._SupplierName;
		}
		set
		{
			if ((this._SupplierName != value))
			{
				this.OnSupplierNameChanging(value);
				this.SendPropertyChanging();
				this._SupplierName = value;
				this.SendPropertyChanged("SupplierName");
				this.OnSupplierNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Barcode", DbType="VarChar(50)")]
	public string Barcode
	{
		get
		{
			return this._Barcode;
		}
		set
		{
			if ((this._Barcode != value))
			{
				this.OnBarcodeChanging(value);
				this.SendPropertyChanging();
				this._Barcode = value;
				this.SendPropertyChanged("Barcode");
				this.OnBarcodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50)")]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleCode", DbType="VarChar(50)")]
	public string StyleCode
	{
		get
		{
			return this._StyleCode;
		}
		set
		{
			if ((this._StyleCode != value))
			{
				this.OnStyleCodeChanging(value);
				this.SendPropertyChanging();
				this._StyleCode = value;
				this.SendPropertyChanged("StyleCode");
				this.OnStyleCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDesc", DbType="VarChar(50)")]
	public string ItemDesc
	{
		get
		{
			return this._ItemDesc;
		}
		set
		{
			if ((this._ItemDesc != value))
			{
				this.OnItemDescChanging(value);
				this.SendPropertyChanging();
				this._ItemDesc = value;
				this.SendPropertyChanged("ItemDesc");
				this.OnItemDescChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
	public System.Nullable<double> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Money")]
	public System.Nullable<decimal> MRP
	{
		get
		{
			return this._MRP;
		}
		set
		{
			if ((this._MRP != value))
			{
				this.OnMRPChanging(value);
				this.SendPropertyChanging();
				this._MRP = value;
				this.SendPropertyChanged("MRP");
				this.OnMRPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRPValue", DbType="Money")]
	public System.Nullable<decimal> MRPValue
	{
		get
		{
			return this._MRPValue;
		}
		set
		{
			if ((this._MRPValue != value))
			{
				this.OnMRPValueChanging(value);
				this.SendPropertyChanging();
				this._MRPValue = value;
				this.SendPropertyChanged("MRPValue");
				this.OnMRPValueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money")]
	public System.Nullable<decimal> Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostValue", DbType="Money")]
	public System.Nullable<decimal> CostValue
	{
		get
		{
			return this._CostValue;
		}
		set
		{
			if ((this._CostValue != value))
			{
				this.OnCostValueChanging(value);
				this.SendPropertyChanging();
				this._CostValue = value;
				this.SendPropertyChanged("CostValue");
				this.OnCostValueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxAmt", DbType="Money")]
	public System.Nullable<decimal> TaxAmt
	{
		get
		{
			return this._TaxAmt;
		}
		set
		{
			if ((this._TaxAmt != value))
			{
				this.OnTaxAmtChanging(value);
				this.SendPropertyChanging();
				this._TaxAmt = value;
				this.SendPropertyChanged("TaxAmt");
				this.OnTaxAmtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportDate", DbType="DateTime NOT NULL")]
	public System.DateTime ImportDate
	{
		get
		{
			return this._ImportDate;
		}
		set
		{
			if ((this._ImportDate != value))
			{
				this.OnImportDateChanging(value);
				this.SendPropertyChanging();
				this._ImportDate = value;
				this.SendPropertyChanged("ImportDate");
				this.OnImportDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDataConsumed", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string IsDataConsumed
	{
		get
		{
			return this._IsDataConsumed;
		}
		set
		{
			if ((this._IsDataConsumed != value))
			{
				this.OnIsDataConsumedChanging(value);
				this.SendPropertyChanging();
				this._IsDataConsumed = value;
				this.SendPropertyChanged("IsDataConsumed");
				this.OnIsDataConsumedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.purchaseRegister")]
public partial class PurchaseRegister : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private System.Nullable<int> _GRNNo;
	
	private System.Nullable<System.DateTime> _GRNDate;
	
	private string _InvoiceNo;
	
	private System.Nullable<System.DateTime> _InvoiceDate;
	
	private string _SupplierName;
	
	private System.Nullable<double> _Quantity;
	
	private System.Nullable<decimal> _MRP;
	
	private System.Nullable<decimal> _MRPValue;
	
	private System.Nullable<decimal> _Cost;
	
	private System.Nullable<decimal> _CostValue;
	
	private System.Nullable<decimal> _TaxAmt;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGRNNoChanging(System.Nullable<int> value);
    partial void OnGRNNoChanged();
    partial void OnGRNDateChanging(System.Nullable<System.DateTime> value);
    partial void OnGRNDateChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnInvoiceDateChanging(System.Nullable<System.DateTime> value);
    partial void OnInvoiceDateChanged();
    partial void OnSupplierNameChanging(string value);
    partial void OnSupplierNameChanged();
    partial void OnQuantityChanging(System.Nullable<double> value);
    partial void OnQuantityChanged();
    partial void OnMRPChanging(System.Nullable<decimal> value);
    partial void OnMRPChanged();
    partial void OnMRPValueChanging(System.Nullable<decimal> value);
    partial void OnMRPValueChanged();
    partial void OnCostChanging(System.Nullable<decimal> value);
    partial void OnCostChanged();
    partial void OnCostValueChanging(System.Nullable<decimal> value);
    partial void OnCostValueChanged();
    partial void OnTaxAmtChanging(System.Nullable<decimal> value);
    partial void OnTaxAmtChanged();
    #endregion
	
	public PurchaseRegister()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNNo", DbType="Int")]
	public System.Nullable<int> GRNNo
	{
		get
		{
			return this._GRNNo;
		}
		set
		{
			if ((this._GRNNo != value))
			{
				this.OnGRNNoChanging(value);
				this.SendPropertyChanging();
				this._GRNNo = value;
				this.SendPropertyChanged("GRNNo");
				this.OnGRNNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRNDate", DbType="Date")]
	public System.Nullable<System.DateTime> GRNDate
	{
		get
		{
			return this._GRNDate;
		}
		set
		{
			if ((this._GRNDate != value))
			{
				this.OnGRNDateChanging(value);
				this.SendPropertyChanging();
				this._GRNDate = value;
				this.SendPropertyChanged("GRNDate");
				this.OnGRNDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="VarChar(50)")]
	public string InvoiceNo
	{
		get
		{
			return this._InvoiceNo;
		}
		set
		{
			if ((this._InvoiceNo != value))
			{
				this.OnInvoiceNoChanging(value);
				this.SendPropertyChanging();
				this._InvoiceNo = value;
				this.SendPropertyChanged("InvoiceNo");
				this.OnInvoiceNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="Date")]
	public System.Nullable<System.DateTime> InvoiceDate
	{
		get
		{
			return this._InvoiceDate;
		}
		set
		{
			if ((this._InvoiceDate != value))
			{
				this.OnInvoiceDateChanging(value);
				this.SendPropertyChanging();
				this._InvoiceDate = value;
				this.SendPropertyChanged("InvoiceDate");
				this.OnInvoiceDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplierName", DbType="VarChar(50)")]
	public string SupplierName
	{
		get
		{
			return this._SupplierName;
		}
		set
		{
			if ((this._SupplierName != value))
			{
				this.OnSupplierNameChanging(value);
				this.SendPropertyChanging();
				this._SupplierName = value;
				this.SendPropertyChanged("SupplierName");
				this.OnSupplierNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Quantity", DbType="Float")]
	public System.Nullable<double> Quantity
	{
		get
		{
			return this._Quantity;
		}
		set
		{
			if ((this._Quantity != value))
			{
				this.OnQuantityChanging(value);
				this.SendPropertyChanging();
				this._Quantity = value;
				this.SendPropertyChanged("Quantity");
				this.OnQuantityChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Money")]
	public System.Nullable<decimal> MRP
	{
		get
		{
			return this._MRP;
		}
		set
		{
			if ((this._MRP != value))
			{
				this.OnMRPChanging(value);
				this.SendPropertyChanging();
				this._MRP = value;
				this.SendPropertyChanged("MRP");
				this.OnMRPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRPValue", DbType="Money")]
	public System.Nullable<decimal> MRPValue
	{
		get
		{
			return this._MRPValue;
		}
		set
		{
			if ((this._MRPValue != value))
			{
				this.OnMRPValueChanging(value);
				this.SendPropertyChanging();
				this._MRPValue = value;
				this.SendPropertyChanged("MRPValue");
				this.OnMRPValueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cost", DbType="Money")]
	public System.Nullable<decimal> Cost
	{
		get
		{
			return this._Cost;
		}
		set
		{
			if ((this._Cost != value))
			{
				this.OnCostChanging(value);
				this.SendPropertyChanging();
				this._Cost = value;
				this.SendPropertyChanged("Cost");
				this.OnCostChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CostValue", DbType="Money")]
	public System.Nullable<decimal> CostValue
	{
		get
		{
			return this._CostValue;
		}
		set
		{
			if ((this._CostValue != value))
			{
				this.OnCostValueChanging(value);
				this.SendPropertyChanging();
				this._CostValue = value;
				this.SendPropertyChanged("CostValue");
				this.OnCostValueChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxAmt", DbType="Money")]
	public System.Nullable<decimal> TaxAmt
	{
		get
		{
			return this._TaxAmt;
		}
		set
		{
			if ((this._TaxAmt != value))
			{
				this.OnTaxAmtChanging(value);
				this.SendPropertyChanging();
				this._TaxAmt = value;
				this.SendPropertyChanged("TaxAmt");
				this.OnTaxAmtChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Sales")]
public partial class Sale : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _InvoiceNo;
	
	private string _InvoiceDate;
	
	private string _InvoiceType;
	
	private string _BrandName;
	
	private string _ProductName;
	
	private string _ItemDescrpetion;
	
	private string _BarCode;
	
	private string _StyleCode;
	
	private double _Qty;
	
	private System.Nullable<decimal> _MRP;
	
	private System.Nullable<decimal> _Discount;
	
	private System.Nullable<decimal> _BasicAmt;
	
	private System.Nullable<decimal> _TaxAmount;
	
	private System.Nullable<decimal> _LineTotal;
	
	private System.Nullable<decimal> _RoundOff;
	
	private System.Nullable<decimal> _BillAmount;
	
	private string _Salesman;
	
	private string _PaymentMode;
	
	private string _HSNCode;
	
	private System.Nullable<decimal> _SGST;
	
	private System.Nullable<decimal> _CGST;
	
	private string _LP;
	
	private System.Nullable<System.DateTime> _ImportDate;
	
	private string _IsDataConsumed;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnInvoiceDateChanging(string value);
    partial void OnInvoiceDateChanged();
    partial void OnInvoiceTypeChanging(string value);
    partial void OnInvoiceTypeChanged();
    partial void OnBrandNameChanging(string value);
    partial void OnBrandNameChanged();
    partial void OnProductNameChanging(string value);
    partial void OnProductNameChanged();
    partial void OnItemDescrpetionChanging(string value);
    partial void OnItemDescrpetionChanged();
    partial void OnBarCodeChanging(string value);
    partial void OnBarCodeChanged();
    partial void OnStyleCodeChanging(string value);
    partial void OnStyleCodeChanged();
    partial void OnQtyChanging(double value);
    partial void OnQtyChanged();
    partial void OnMRPChanging(System.Nullable<decimal> value);
    partial void OnMRPChanged();
    partial void OnDiscountChanging(System.Nullable<decimal> value);
    partial void OnDiscountChanged();
    partial void OnBasicAmtChanging(System.Nullable<decimal> value);
    partial void OnBasicAmtChanged();
    partial void OnTaxAmountChanging(System.Nullable<decimal> value);
    partial void OnTaxAmountChanged();
    partial void OnLineTotalChanging(System.Nullable<decimal> value);
    partial void OnLineTotalChanged();
    partial void OnRoundOffChanging(System.Nullable<decimal> value);
    partial void OnRoundOffChanged();
    partial void OnBillAmountChanging(System.Nullable<decimal> value);
    partial void OnBillAmountChanged();
    partial void OnSalesmanChanging(string value);
    partial void OnSalesmanChanged();
    partial void OnPaymentModeChanging(string value);
    partial void OnPaymentModeChanged();
    partial void OnHSNCodeChanging(string value);
    partial void OnHSNCodeChanged();
    partial void OnSGSTChanging(System.Nullable<decimal> value);
    partial void OnSGSTChanged();
    partial void OnCGSTChanging(System.Nullable<decimal> value);
    partial void OnCGSTChanged();
    partial void OnLPChanging(string value);
    partial void OnLPChanged();
    partial void OnImportDateChanging(System.Nullable<System.DateTime> value);
    partial void OnImportDateChanged();
    partial void OnIsDataConsumedChanging(string value);
    partial void OnIsDataConsumedChanged();
    #endregion
	
	public Sale()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="VarChar(50)")]
	public string InvoiceNo
	{
		get
		{
			return this._InvoiceNo;
		}
		set
		{
			if ((this._InvoiceNo != value))
			{
				this.OnInvoiceNoChanging(value);
				this.SendPropertyChanging();
				this._InvoiceNo = value;
				this.SendPropertyChanged("InvoiceNo");
				this.OnInvoiceNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="VarChar(50)")]
	public string InvoiceDate
	{
		get
		{
			return this._InvoiceDate;
		}
		set
		{
			if ((this._InvoiceDate != value))
			{
				this.OnInvoiceDateChanging(value);
				this.SendPropertyChanging();
				this._InvoiceDate = value;
				this.SendPropertyChanged("InvoiceDate");
				this.OnInvoiceDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="VarChar(50)")]
	public string InvoiceType
	{
		get
		{
			return this._InvoiceType;
		}
		set
		{
			if ((this._InvoiceType != value))
			{
				this.OnInvoiceTypeChanging(value);
				this.SendPropertyChanging();
				this._InvoiceType = value;
				this.SendPropertyChanged("InvoiceType");
				this.OnInvoiceTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BrandName", DbType="VarChar(50)")]
	public string BrandName
	{
		get
		{
			return this._BrandName;
		}
		set
		{
			if ((this._BrandName != value))
			{
				this.OnBrandNameChanging(value);
				this.SendPropertyChanging();
				this._BrandName = value;
				this.SendPropertyChanged("BrandName");
				this.OnBrandNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductName", DbType="VarChar(50)")]
	public string ProductName
	{
		get
		{
			return this._ProductName;
		}
		set
		{
			if ((this._ProductName != value))
			{
				this.OnProductNameChanging(value);
				this.SendPropertyChanging();
				this._ProductName = value;
				this.SendPropertyChanged("ProductName");
				this.OnProductNameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemDescrpetion", DbType="VarChar(50)")]
	public string ItemDescrpetion
	{
		get
		{
			return this._ItemDescrpetion;
		}
		set
		{
			if ((this._ItemDescrpetion != value))
			{
				this.OnItemDescrpetionChanging(value);
				this.SendPropertyChanging();
				this._ItemDescrpetion = value;
				this.SendPropertyChanged("ItemDescrpetion");
				this.OnItemDescrpetionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BarCode", DbType="VarChar(50)")]
	public string BarCode
	{
		get
		{
			return this._BarCode;
		}
		set
		{
			if ((this._BarCode != value))
			{
				this.OnBarCodeChanging(value);
				this.SendPropertyChanging();
				this._BarCode = value;
				this.SendPropertyChanged("BarCode");
				this.OnBarCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleCode", DbType="VarChar(50)")]
	public string StyleCode
	{
		get
		{
			return this._StyleCode;
		}
		set
		{
			if ((this._StyleCode != value))
			{
				this.OnStyleCodeChanging(value);
				this.SendPropertyChanging();
				this._StyleCode = value;
				this.SendPropertyChanged("StyleCode");
				this.OnStyleCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Float NOT NULL")]
	public double Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this.OnQtyChanging(value);
				this.SendPropertyChanging();
				this._Qty = value;
				this.SendPropertyChanged("Qty");
				this.OnQtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Money")]
	public System.Nullable<decimal> MRP
	{
		get
		{
			return this._MRP;
		}
		set
		{
			if ((this._MRP != value))
			{
				this.OnMRPChanging(value);
				this.SendPropertyChanging();
				this._MRP = value;
				this.SendPropertyChanged("MRP");
				this.OnMRPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Money")]
	public System.Nullable<decimal> Discount
	{
		get
		{
			return this._Discount;
		}
		set
		{
			if ((this._Discount != value))
			{
				this.OnDiscountChanging(value);
				this.SendPropertyChanging();
				this._Discount = value;
				this.SendPropertyChanged("Discount");
				this.OnDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicAmt", DbType="Money")]
	public System.Nullable<decimal> BasicAmt
	{
		get
		{
			return this._BasicAmt;
		}
		set
		{
			if ((this._BasicAmt != value))
			{
				this.OnBasicAmtChanging(value);
				this.SendPropertyChanging();
				this._BasicAmt = value;
				this.SendPropertyChanged("BasicAmt");
				this.OnBasicAmtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxAmount", DbType="Money")]
	public System.Nullable<decimal> TaxAmount
	{
		get
		{
			return this._TaxAmount;
		}
		set
		{
			if ((this._TaxAmount != value))
			{
				this.OnTaxAmountChanging(value);
				this.SendPropertyChanging();
				this._TaxAmount = value;
				this.SendPropertyChanged("TaxAmount");
				this.OnTaxAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LineTotal", DbType="Money")]
	public System.Nullable<decimal> LineTotal
	{
		get
		{
			return this._LineTotal;
		}
		set
		{
			if ((this._LineTotal != value))
			{
				this.OnLineTotalChanging(value);
				this.SendPropertyChanging();
				this._LineTotal = value;
				this.SendPropertyChanged("LineTotal");
				this.OnLineTotalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundOff", DbType="Money")]
	public System.Nullable<decimal> RoundOff
	{
		get
		{
			return this._RoundOff;
		}
		set
		{
			if ((this._RoundOff != value))
			{
				this.OnRoundOffChanging(value);
				this.SendPropertyChanging();
				this._RoundOff = value;
				this.SendPropertyChanged("RoundOff");
				this.OnRoundOffChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAmount", DbType="Money")]
	public System.Nullable<decimal> BillAmount
	{
		get
		{
			return this._BillAmount;
		}
		set
		{
			if ((this._BillAmount != value))
			{
				this.OnBillAmountChanging(value);
				this.SendPropertyChanging();
				this._BillAmount = value;
				this.SendPropertyChanged("BillAmount");
				this.OnBillAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Salesman", DbType="VarChar(50)")]
	public string Salesman
	{
		get
		{
			return this._Salesman;
		}
		set
		{
			if ((this._Salesman != value))
			{
				this.OnSalesmanChanging(value);
				this.SendPropertyChanging();
				this._Salesman = value;
				this.SendPropertyChanged("Salesman");
				this.OnSalesmanChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMode", DbType="VarChar(50)")]
	public string PaymentMode
	{
		get
		{
			return this._PaymentMode;
		}
		set
		{
			if ((this._PaymentMode != value))
			{
				this.OnPaymentModeChanging(value);
				this.SendPropertyChanging();
				this._PaymentMode = value;
				this.SendPropertyChanged("PaymentMode");
				this.OnPaymentModeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HSNCode", DbType="VarChar(50)")]
	public string HSNCode
	{
		get
		{
			return this._HSNCode;
		}
		set
		{
			if ((this._HSNCode != value))
			{
				this.OnHSNCodeChanging(value);
				this.SendPropertyChanging();
				this._HSNCode = value;
				this.SendPropertyChanged("HSNCode");
				this.OnHSNCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGST", DbType="Money")]
	public System.Nullable<decimal> SGST
	{
		get
		{
			return this._SGST;
		}
		set
		{
			if ((this._SGST != value))
			{
				this.OnSGSTChanging(value);
				this.SendPropertyChanging();
				this._SGST = value;
				this.SendPropertyChanged("SGST");
				this.OnSGSTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CGST", DbType="Money")]
	public System.Nullable<decimal> CGST
	{
		get
		{
			return this._CGST;
		}
		set
		{
			if ((this._CGST != value))
			{
				this.OnCGSTChanging(value);
				this.SendPropertyChanging();
				this._CGST = value;
				this.SendPropertyChanged("CGST");
				this.OnCGSTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LP", DbType="VarChar(50)")]
	public string LP
	{
		get
		{
			return this._LP;
		}
		set
		{
			if ((this._LP != value))
			{
				this.OnLPChanging(value);
				this.SendPropertyChanging();
				this._LP = value;
				this.SendPropertyChanged("LP");
				this.OnLPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImportDate", DbType="DateTime")]
	public System.Nullable<System.DateTime> ImportDate
	{
		get
		{
			return this._ImportDate;
		}
		set
		{
			if ((this._ImportDate != value))
			{
				this.OnImportDateChanging(value);
				this.SendPropertyChanging();
				this._ImportDate = value;
				this.SendPropertyChanged("ImportDate");
				this.OnImportDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDataConsumed", DbType="VarChar(50)")]
	public string IsDataConsumed
	{
		get
		{
			return this._IsDataConsumed;
		}
		set
		{
			if ((this._IsDataConsumed != value))
			{
				this.OnIsDataConsumedChanging(value);
				this.SendPropertyChanging();
				this._IsDataConsumed = value;
				this.SendPropertyChanged("IsDataConsumed");
				this.OnIsDataConsumedChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SalesRegister")]
public partial class SalesRegister : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _Id;
	
	private string _InvoiceNo;
	
	private string _InvoiceDate;
	
	private string _InvoiceType;
	
	private int _Qty;
	
	private decimal _MRP;
	
	private decimal _Discount;
	
	private decimal _BasicAmt;
	
	private decimal _TaxAmount;
	
	private decimal _RoundOff;
	
	private decimal _BillAmount;
	
	private string _PaymentMode;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnInvoiceNoChanging(string value);
    partial void OnInvoiceNoChanged();
    partial void OnInvoiceDateChanging(string value);
    partial void OnInvoiceDateChanged();
    partial void OnInvoiceTypeChanging(string value);
    partial void OnInvoiceTypeChanged();
    partial void OnQtyChanging(int value);
    partial void OnQtyChanged();
    partial void OnMRPChanging(decimal value);
    partial void OnMRPChanged();
    partial void OnDiscountChanging(decimal value);
    partial void OnDiscountChanged();
    partial void OnBasicAmtChanging(decimal value);
    partial void OnBasicAmtChanged();
    partial void OnTaxAmountChanging(decimal value);
    partial void OnTaxAmountChanged();
    partial void OnRoundOffChanging(decimal value);
    partial void OnRoundOffChanged();
    partial void OnBillAmountChanging(decimal value);
    partial void OnBillAmountChanged();
    partial void OnPaymentModeChanging(string value);
    partial void OnPaymentModeChanged();
    #endregion
	
	public SalesRegister()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this.OnIdChanging(value);
				this.SendPropertyChanging();
				this._Id = value;
				this.SendPropertyChanged("Id");
				this.OnIdChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceNo", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string InvoiceNo
	{
		get
		{
			return this._InvoiceNo;
		}
		set
		{
			if ((this._InvoiceNo != value))
			{
				this.OnInvoiceNoChanging(value);
				this.SendPropertyChanging();
				this._InvoiceNo = value;
				this.SendPropertyChanged("InvoiceNo");
				this.OnInvoiceNoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceDate", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string InvoiceDate
	{
		get
		{
			return this._InvoiceDate;
		}
		set
		{
			if ((this._InvoiceDate != value))
			{
				this.OnInvoiceDateChanging(value);
				this.SendPropertyChanging();
				this._InvoiceDate = value;
				this.SendPropertyChanged("InvoiceDate");
				this.OnInvoiceDateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InvoiceType", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string InvoiceType
	{
		get
		{
			return this._InvoiceType;
		}
		set
		{
			if ((this._InvoiceType != value))
			{
				this.OnInvoiceTypeChanging(value);
				this.SendPropertyChanging();
				this._InvoiceType = value;
				this.SendPropertyChanged("InvoiceType");
				this.OnInvoiceTypeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qty", DbType="Int NOT NULL")]
	public int Qty
	{
		get
		{
			return this._Qty;
		}
		set
		{
			if ((this._Qty != value))
			{
				this.OnQtyChanging(value);
				this.SendPropertyChanging();
				this._Qty = value;
				this.SendPropertyChanged("Qty");
				this.OnQtyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MRP", DbType="Money NOT NULL")]
	public decimal MRP
	{
		get
		{
			return this._MRP;
		}
		set
		{
			if ((this._MRP != value))
			{
				this.OnMRPChanging(value);
				this.SendPropertyChanging();
				this._MRP = value;
				this.SendPropertyChanged("MRP");
				this.OnMRPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Discount", DbType="Money NOT NULL")]
	public decimal Discount
	{
		get
		{
			return this._Discount;
		}
		set
		{
			if ((this._Discount != value))
			{
				this.OnDiscountChanging(value);
				this.SendPropertyChanging();
				this._Discount = value;
				this.SendPropertyChanged("Discount");
				this.OnDiscountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BasicAmt", DbType="Money NOT NULL")]
	public decimal BasicAmt
	{
		get
		{
			return this._BasicAmt;
		}
		set
		{
			if ((this._BasicAmt != value))
			{
				this.OnBasicAmtChanging(value);
				this.SendPropertyChanging();
				this._BasicAmt = value;
				this.SendPropertyChanged("BasicAmt");
				this.OnBasicAmtChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxAmount", DbType="Money NOT NULL")]
	public decimal TaxAmount
	{
		get
		{
			return this._TaxAmount;
		}
		set
		{
			if ((this._TaxAmount != value))
			{
				this.OnTaxAmountChanging(value);
				this.SendPropertyChanging();
				this._TaxAmount = value;
				this.SendPropertyChanged("TaxAmount");
				this.OnTaxAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RoundOff", DbType="Money NOT NULL")]
	public decimal RoundOff
	{
		get
		{
			return this._RoundOff;
		}
		set
		{
			if ((this._RoundOff != value))
			{
				this.OnRoundOffChanging(value);
				this.SendPropertyChanging();
				this._RoundOff = value;
				this.SendPropertyChanged("RoundOff");
				this.OnRoundOffChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BillAmount", DbType="Money NOT NULL")]
	public decimal BillAmount
	{
		get
		{
			return this._BillAmount;
		}
		set
		{
			if ((this._BillAmount != value))
			{
				this.OnBillAmountChanging(value);
				this.SendPropertyChanging();
				this._BillAmount = value;
				this.SendPropertyChanged("BillAmount");
				this.OnBillAmountChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PaymentMode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string PaymentMode
	{
		get
		{
			return this._PaymentMode;
		}
		set
		{
			if ((this._PaymentMode != value))
			{
				this.OnPaymentModeChanging(value);
				this.SendPropertyChanging();
				this._PaymentMode = value;
				this.SendPropertyChanged("PaymentMode");
				this.OnPaymentModeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Users")]
public partial class User
{
	
	private int _Id;
	
	private string _Username;
	
	private string _Passwd;
	
	private int _Role;
	
	public User()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
	public int Id
	{
		get
		{
			return this._Id;
		}
		set
		{
			if ((this._Id != value))
			{
				this._Id = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="username", Storage="_Username", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string Username
	{
		get
		{
			return this._Username;
		}
		set
		{
			if ((this._Username != value))
			{
				this._Username = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="passwd", Storage="_Passwd", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Passwd
	{
		get
		{
			return this._Passwd;
		}
		set
		{
			if ((this._Passwd != value))
			{
				this._Passwd = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="role", Storage="_Role", DbType="Int NOT NULL")]
	public int Role
	{
		get
		{
			return this._Role;
		}
		set
		{
			if ((this._Role != value))
			{
				this._Role = value;
			}
		}
	}
}
#pragma warning restore 1591
