//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDataBase.ERDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsertDataLog
    {
        public int ID { get; set; }
        public string BillNumber { get; set; }
        public int VoyBillId { get; set; }
        public byte[] CreatedDate { get; set; }
        public System.DateTime InsertedOn { get; set; }
        public Nullable<int> SaleInvoiceId { get; set; }
        public Nullable<int> DailySaleId { get; set; }
        public string Remark { get; set; }
    }
}
