//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDataBase.ERDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VoyBill
    {
        public int ID { get; set; }
        public string BillType { get; set; }
        public string BillNumber { get; set; }
        public Nullable<System.DateTime> BillTime { get; set; }
        public double BillAmount { get; set; }
        public double BillGrossAmount { get; set; }
        public double BillDiscount { get; set; }
        public string CustomerName { get; set; }
        public string CustomerMobile { get; set; }
        public string StoreID { get; set; }
    }
}
