//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDataBase.ERDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VoygerDatabaseEntities : DbContext
    {
        public VoygerDatabaseEntities()
            : base("name=VoygerDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InsertDataLog> InsertDataLogs { get; set; }
        public virtual DbSet<LineItem> LineItems { get; set; }
        public virtual DbSet<VoyBill> VoyBills { get; set; }
        public virtual DbSet<VPaymentMode> VPaymentModes { get; set; }
    }
}
