//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDataBase.ERDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class VPaymentMode
    {
        public int ID { get; set; }
        public int VoyBillId { get; set; }
        public string PaymentMode { get; set; }
        public string PaymentValue { get; set; }
        public string Notes { get; set; }
    }
}
