//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankDetail()
        {
            this.Expenses = new HashSet<Expens>();
        }
    
        public int BankDetailsID { get; set; }
        public string RefID { get; set; }
        public int BankID { get; set; }
        public Nullable<int> TranscationType { get; set; }
        public string BankRef { get; set; }
        public string TranscationRef { get; set; }
    
        public virtual Bank Bank { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expens> Expenses { get; set; }
    }
}
