//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class CardPaymentDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CardPaymentDetail()
        {
            this.PaymentDetails = new HashSet<PaymentDetail>();
        }
    
        public int CardPaymentDetailsID { get; set; }
        public string InvoiceNo { get; set; }
        public int CardType { get; set; }
        public decimal Amount { get; set; }
        public Nullable<int> AuthCode { get; set; }
        public Nullable<int> LastDigit { get; set; }
    
        public virtual SaleInvoice SaleInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentDetail> PaymentDetails { get; set; }
    }
}
