//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class DailySale
    {
        public int DailySaleID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int CustomerID { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<int> RMZ { get; set; }
        public Nullable<int> Fabric { get; set; }
        public Nullable<int> Tailoring { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
    }
}
