//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayClosing
    {
        public int DayClosingID { get; set; }
        public System.DateTime OnDate { get; set; }
        public int TotalAmount { get; set; }
        public Nullable<int> C2000 { get; set; }
        public Nullable<int> C200 { get; set; }
        public Nullable<int> C1000 { get; set; }
        public Nullable<int> C500 { get; set; }
        public Nullable<int> C100 { get; set; }
        public Nullable<int> C50 { get; set; }
        public Nullable<int> C20 { get; set; }
        public Nullable<int> C10 { get; set; }
        public Nullable<int> C5 { get; set; }
        public Nullable<int> Coin10 { get; set; }
        public Nullable<int> Coin5 { get; set; }
        public Nullable<int> Coin2 { get; set; }
        public Nullable<int> Coin1 { get; set; }
    }
}
