//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expens
    {
        public int ExpensesID { get; set; }
        public Nullable<int> ExpensesCategoryID { get; set; }
        public string ExpensesReason { get; set; }
        public string ApprovedBy { get; set; }
        public Nullable<int> PaymentModeID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> BankDetailsID { get; set; }
    
        public virtual BankDetail BankDetail { get; set; }
        public virtual ExpensesCategory ExpensesCategory { get; set; }
        public virtual PaymentMode PaymentMode { get; set; }
    }
}
