//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRegister
    {
        public int PurchaseRegisterID { get; set; }
        public Nullable<int> GRNNo { get; set; }
        public Nullable<System.DateTime> GRNDate { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string SupplierName { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> MRPValue { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public Nullable<decimal> CostValue { get; set; }
        public Nullable<decimal> TaxAmt { get; set; }
    }
}
