//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int SalesId { get; set; }
        public string InvoiceNo { get; set; }
        public string InvoiceDate { get; set; }
        public string InvoiceType { get; set; }
        public string BrandName { get; set; }
        public string ProductName { get; set; }
        public string ItemDescrpetion { get; set; }
        public string BarCode { get; set; }
        public string StyleCode { get; set; }
        public double Qty { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> BasicAmt { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> LineTotal { get; set; }
        public Nullable<decimal> RoundOff { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public string Salesman { get; set; }
        public string PaymentMode { get; set; }
        public string HSNCode { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public string LP { get; set; }
        public Nullable<System.DateTime> ImportDate { get; set; }
        public string IsDataConsumed { get; set; }
    }
}
