//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class SaleItem
    {
        public int SaleItemID { get; set; }
        public string InvoiceNo { get; set; }
        public string BarCode { get; set; }
        public decimal Qty { get; set; }
        public Nullable<decimal> MRP { get; set; }
        public Nullable<decimal> BasicAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Tax { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public int SalesmanID { get; set; }
        public Nullable<double> IGSTRate { get; set; }
        public Nullable<double> CGSTRate { get; set; }
        public Nullable<double> SGSTRate { get; set; }
        public Nullable<decimal> CGST { get; set; }
        public Nullable<decimal> SGST { get; set; }
        public int IsManualBill { get; set; }
        public int IsAdjusted { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
        public virtual SaleInvoice SaleInvoice { get; set; }
        public virtual Salesman Salesman { get; set; }
    }
}
