//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprajitaRetailsDB.DAL.AprajitaRetails
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockSale
    {
        public int StockSaleID { get; set; }
        public string BarCode { get; set; }
        public double Qty { get; set; }
        public Nullable<double> MQty { get; set; }
        public Nullable<double> AcutalQty { get; set; }
    
        public virtual ProductItem ProductItem { get; set; }
    }
}
